# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'binocular.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1430, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 50, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1020, 50, 54, 12))
        self.label_2.setObjectName("label_2")
        self.left_frame = QtWidgets.QLabel(self.centralwidget)
        self.left_frame.setGeometry(QtCore.QRect(50, 100, 640, 480))
        self.left_frame.setObjectName("left_frame")
        self.right_frame = QtWidgets.QLabel(self.centralwidget)
        self.right_frame.setGeometry(QtCore.QRect(740, 100, 640, 480))
        self.right_frame.setObjectName("right_frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 630, 1321, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_camera_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.open_camera_Btn.setObjectName("open_camera_Btn")
        self.horizontalLayout.addWidget(self.open_camera_Btn)
        self.open_binocular_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.open_binocular_Btn.setObjectName("open_binocular_Btn")
        self.horizontalLayout.addWidget(self.open_binocular_Btn)
        self.capture_calibration_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.capture_calibration_Btn.setObjectName("capture_calibration_Btn")
        self.horizontalLayout.addWidget(self.capture_calibration_Btn)
        self.binocular_calibration_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.binocular_calibration_Btn.setBaseSize(QtCore.QSize(0, 50))
        self.binocular_calibration_Btn.setObjectName("binocular_calibration_Btn")
        self.horizontalLayout.addWidget(self.binocular_calibration_Btn)
        self.capture_calculate_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.capture_calculate_Btn.setObjectName("capture_calculate_Btn")
        self.horizontalLayout.addWidget(self.capture_calculate_Btn)
        self.continue_calculate_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.continue_calculate_Btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continue_calculate_Btn.sizePolicy().hasHeightForWidth())
        self.continue_calculate_Btn.setSizePolicy(sizePolicy)
        self.continue_calculate_Btn.setBaseSize(QtCore.QSize(0, 50))
        self.continue_calculate_Btn.setObjectName("continue_calculate_Btn")
        self.horizontalLayout.addWidget(self.continue_calculate_Btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1430, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "left"))
        self.label_2.setText(_translate("MainWindow", "right"))
        self.left_frame.setText(_translate("MainWindow", "TextLabel"))
        self.right_frame.setText(_translate("MainWindow", "TextLabel"))
        self.open_camera_Btn.setText(_translate("MainWindow", "Open Camera"))
        self.open_binocular_Btn.setText(_translate("MainWindow", "Open binocular Images"))
        self.capture_calibration_Btn.setText(_translate("MainWindow", "Capture Calibration"))
        self.binocular_calibration_Btn.setText(_translate("MainWindow", "Binocular Calibration"))
        self.capture_calculate_Btn.setText(_translate("MainWindow", "Capture and Calculate（calibrationed）"))
        self.continue_calculate_Btn.setText(_translate("MainWindow", "Capture and Calculate（no calibration）"))
